<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2017-04-23 10:35:51
 */
return [
    'all' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/public',
        'baseUrl' => '@web/public',
        'js' => [],
        'css' => [],
        'depends' => [],
        'sourcePath' => null,
    ],
    'back' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/public',
        'baseUrl' => '@web/public',
        'js' => [
            'js/back-a93f00c65e36cbc9eeac6b68c380a408.js',
        ],
        'css' => [
            'css/back-af27f0da82f8e2d69317d533eb64c16d.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'app\\themes\\basic\\BackgroundAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'back',
        ],
    ],
];