<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2017-04-04 15:23:25
 */
return [
    'all' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js/all-77d3fad1bc257dce69f79dda801387ad.js',
        ],
        'css' => [
            'css/all-3572c455f98394bdd101e7f0c3b6c91f.css',
        ],
        'sourcePath' => null,
        'depends' => [],
    ],
    'app\\themes\\basic\\BackgroundAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
];