<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2017-05-02 17:07:01
 */
return [
    'all' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/public',
        'baseUrl' => '@web/public',
        'js' => [
            'js/all-d41d8cd98f00b204e9800998ecf8427e.js',
        ],
        'css' => [
            'css/all-e438e0c4958c5c30e42bc551b0549ebc.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'back' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/public',
        'baseUrl' => '@web/public',
        'js' => [
            'js/back-0fc070000c5631096649cc36ae03e469.js',
        ],
        'css' => [
            'css/back-0ebc02d6f3b521ee4acac02e8c63a49f.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'yii\\bootstrap\\BootstrapPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'yii\\bootstrap\\BootstrapAsset',
            'all',
        ],
    ],
    'app\\themes\\basic\\BackgroundAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\bootstrap\\BootstrapPluginAsset',
            'back',
        ],
    ],
];