<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2017-05-12 10:49:37
 */
return [
    'all' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/public',
        'baseUrl' => '@web/public',
        'js' => [
            'js/all-f788bd813141eea1d8d07427561f7a3a.js',
        ],
        'css' => [
            'css/all-fb4d3f0dacb202e9180983207ffe2cb8.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'back' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/public',
        'baseUrl' => '@web/public',
        'js' => [
            'js/back-0fc070000c5631096649cc36ae03e469.js',
        ],
        'css' => [
            'css/back-0ebc02d6f3b521ee4acac02e8c63a49f.css',
        ],
        'depends' => [],
        'sourcePath' => null,
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'app\\assets\\BootstrapPluginAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\bootstrap\\BootstrapAsset',
            'all',
        ],
    ],
    'app\\themes\\basic\\BackgroundAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\BootstrapPluginAsset',
            'back',
        ],
    ],
];